In [1]:
import numpy as np

In [3]:
arr = np.random.randint(0,10,(4,4))
print(arr)

[[1 1 5 9]
 [5 1 7 0]
 [5 8 8 2]
 [2 4 2 4]]


In [6]:
print('Mean : ',np.mean(arr, axis=1))
print('Standard Deviation : ', np.std(arr, axis=1))
print('Variance : ', np.var(arr, axis=1))

Mean :  [4.   3.25 5.75 3.  ]
Standard Deviation :  [3.31662479 2.86138079 2.48746859 1.        ]
Variance :  [11.      8.1875  6.1875  1.    ]


In [13]:
B = np.array([56,48,22,41,78,91,24,46,8,33])
print(np.sort(B))
print(np.argsort(B))

[ 8 22 24 33 41 46 48 56 78 91]
[8 2 6 9 3 7 1 0 4 5]


In [28]:
m = int(input('Rows : '))
n = int(input('Columns : '))
l1 = eval(input())
arr1 = np.array(l1).reshape(m,n)
#arr1 = np.arange(1,13).reshape(m,n)
print(arr1)

Rows :  3
Columns :  4
 [1,2,3,4,5,6,7,8,9,10,11,12]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
print(arr1.shape)
print(arr1.dtype)
print(type(arr1))
print(arr1.reshape(n,m))

(3, 4)
int32
<class 'numpy.ndarray'>
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
arr2 = np.random.randint(0,10,(4,4))
print(arr2)

[[2 0 5 3]
 [8 0 7 9]
 [4 3 1 7]
 [5 0 6 9]]


In [39]:
arr3 = np.array(eval(input())).reshape(2,4)
print(arr3)
print('Non Zero elements : ', arr2 != 0)
print('Indices of non zero elements : ', np.argwhere(arr2 != 0))
print(' Zero elements : ', arr2 == 0)
print('Indices of zero elements : ', np.argwhere(arr2 == 0))
print('Nan elements : ', np.isnan(arr3))
print('Indices of nan elements : ', np.argwhere(np.isnan(arr3)))

 [1,2,np.nan,3,4,np.nan,np.nan,5]


[[ 1.  2. nan  3.]
 [ 4. nan nan  5.]]
Non Zero elements :  [[ True False  True  True]
 [ True False  True  True]
 [ True  True  True  True]
 [ True False  True  True]]
Indices of non zero elements :  [[0 0]
 [0 2]
 [0 3]
 [1 0]
 [1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 2]
 [3 3]]
 Zero elements :  [[False  True False False]
 [False  True False False]
 [False False False False]
 [False  True False False]]
Indices of zero elements :  [[0 1]
 [1 1]
 [3 1]]
Nan elements :  [[False False  True False]
 [False  True  True False]]
Indices of nan elements :  [[0 2]
 [1 1]
 [1 2]]
